"""Typed, immutable capability registry for AREMA."""

from arema.registry.catalog import CapabilityCatalog, CatalogBuilder
from arema.registry.descriptors import (
    AfterToolCallback,
    AgentDescriptor,
    AgentFactory,
    AgentKind,
    BeforeModelCallback,
    BeforeToolCallback,
    Callback,
    ContextMode,
    JsonScalar,
    McpServerDescriptor,
    OutputPolicy,
    RuntimeProfile,
    SseTransport,
    StdioTransport,
    StreamableHttpTransport,
    ToolDescriptor,
    ToolErrorCallback,
    ToolFactory,
    ToolLifecycleCallbacks,
    ToolLike,
    ToolMemoryCallback,
)
from arema.registry.errors import (
    CapabilityCycleError,
    CatalogError,
    CatalogFrozenError,
    CatalogValidationError,
    DuplicateCapabilityError,
    InvalidCapabilityDescriptorError,
    InvalidRootError,
    InvalidToolDescriptorError,
    InvalidTransportError,
    MissingEnvironmentValueError,
    UnreachableAgentError,
    UnresolvedCapabilityError,
)

__all__ = [
    "AfterToolCallback",
    "AgentDescriptor",
    "AgentFactory",
    "AgentKind",
    "BeforeModelCallback",
    "BeforeToolCallback",
    "Callback",
    "CapabilityCatalog",
    "CapabilityCycleError",
    "CatalogBuilder",
    "CatalogError",
    "CatalogFrozenError",
    "CatalogValidationError",
    "ContextMode",
    "DuplicateCapabilityError",
    "InvalidCapabilityDescriptorError",
    "InvalidRootError",
    "InvalidToolDescriptorError",
    "InvalidTransportError",
    "JsonScalar",
    "McpServerDescriptor",
    "MissingEnvironmentValueError",
    "OutputPolicy",
    "RuntimeProfile",
    "SseTransport",
    "StdioTransport",
    "StreamableHttpTransport",
    "ToolDescriptor",
    "ToolErrorCallback",
    "ToolFactory",
    "ToolLifecycleCallbacks",
    "ToolLike",
    "ToolMemoryCallback",
    "UnreachableAgentError",
    "UnresolvedCapabilityError",
]
